name: python3

on: 
  - push

jobs:
  find_lowest_number:
    name: Run Python Script
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Repo check
        run: echo "Repo checked out"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run script
        run: |
          python find_lowest_number.py numbers.txt okly.txt
